# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: configuredatabricks@0
  inputs:
    url: 'https://adb-5982401339317117.17.azuredatabricks.net'
    token: 'dapi94019417b4d0216b1eaa0e99741a162e'
  
- task: executenotebook@0
  inputs:
    notebookPath: '/Users/lubraz@microsoft.com/tensorflow-mlops/treino'
    existingClusterId: '0512-164724-work453'