# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Begin MLOps Pipeline !
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: configuredatabricks@0
  inputs:
    url: $(databricks-url)
    token: $(databricks-token)
  
- task: executenotebook@0
  inputs:
    notebookPath: '/Users/lubraz@microsoft.com/tensorflow-mlops/treino'
    existingClusterId: $(databricks-cluster-id)

- task: waitexecution@0

- task: executenotebook@0
  inputs:
    notebookPath: '/Users/lubraz@microsoft.com/tensorflow-mlops/entry'
    existingClusterId: $(databricks-cluster-id)


- task: waitexecution@0

#- task: executenotebook@0
#  inputs:
#    notebookPath: '/Users/lubraz@microsoft.com/tensorflow-mlops/deploy'
#    existingClusterId: $(databricks-cluster-id)

#- task: waitexecution@0